### PR TITLE
Install Dev Channel

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
有两种选择，第一种是只有开发人员才能安装开发频道的脚本
第二种是所有人都可以安装不稳定版本
请大家自便，我都写了

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.

I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 现在总可以了
我没有merge
~~你来选两个功能的一个~~
~~我已经注释掉了~~

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 我让你们review了，不知道这样行不行

**Comment by PythonSmall-Q** [comment]
Wait a sec

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 
image
有什么意义吗？

**Review by PythonSmall-Q — CHANGES_REQUESTED** [review]
不太理解有什么意义

**Comment by zhouyiqing0304** [comment]
哈哈哈

**Comment by zhouyiqing0304** [comment]
懒得在github上装

**Comment by zhouyiqing0304** [comment]
你们submit的东西我们也要看看啊

**Comment by zhouyiqing0304** [comment]
要不然我们自己闷着看稳定版？

**Comment by zhouyiqing0304** [comment]
当然访客身份看不到这个东西

**Comment by zhouyiqing0304** [comment]
~~你要是有兴趣让访客也看到这样的东西的话就把上面一段代码删掉然后解除下面代码的注释~~
~~那访客看到的东西会是这样的~~
image

**Comment by boomzero** [comment]
调试模式

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 你在这里（https://www.xmoj.tech/index.php?ByUserScript=1）翻到最下面打开“调试模式”就可以接受开发组的不稳定更新了

**Pull request closed without merging**
