### PR TITLE
在打开某一个比赛或作业时自动查找签到题并且提交

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
目前还有一个问题：就是每次打开都要这样，待改进

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.

I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@boomzero @PythonSmall-Q 麻烦通过一下

**Comment by boomzero** [comment]
自动提交当年代码

**Comment by zhouyiqing0304** [comment]
我知道，可是自动提交当年代码会给你贴一个“疑似提交当年代码”

**Comment by zhouyiqing0304** [comment]
这也是为什么我要加这个的原因

**Comment by zhouyiqing0304** [comment]
@boomzero

**Comment by boomzero** [comment]
> 我知道，可是自动提交当年代码会给你贴一个“疑似提交当年代码”

那你就别用

**Comment by boomzero** [comment]
我建议你向 linux 或者 git 提交一点代码

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 脚本任何功能触发前都需要用户同意，你这么做让用户失去了知情权是违法的哟！再好的功能也要用户同意

**Comment by PythonSmall-Q** [comment]
@boomzero 话说这个用能看上去也不错

**Comment by PythonSmall-Q** [comment]
你同意的话就repoen，不同意觉得没必要就忽略吧

**Comment by PythonSmall-Q** [comment]
> 目前还有一个问题：就是每次打开都要这样，待改进
> 
> * [x]  我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。
> 
> By making a contribution to this project, I certify that:
> 
> The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or
> 
> The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or
> 
> The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.
> 
> I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

流程而已，没必要诟病

**Pull request closed without merging**
