### PR TITLE
新增下载项并且允许管理员用户直接获取标程

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
允许下载VMware Workstation Pro
允许下载Microsoft Visual Studio
~~允许管理员用户直接获取标程~~

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.

I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 这需不需要更改版本号

**Comment by zhouyiqing0304** [comment]
@boomzero Review一下哈

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q Review一下

**Comment by zhouyiqing0304** [comment]
~~不开玩笑，管理员账户的确可以查看标程，无论分数~~

**Comment by boomzero** [comment]
又一个只改前端不该后端的

**Comment by PythonSmall-Q** [comment]
不是，你tm不该后端

**Pull request merged**
