### PR TITLE
Sync Dev

### PR DESCRIPTION
**Pull request by PythonSmall-Q**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

### CODE REVIEW

**Comment by boomzero** [comment]
...

**Review by boomzero — CHANGES_REQUESTED** [review]
be patient, wait

**Comment by PythonSmall-Q** [comment]
怎么啦

**Comment by boomzero** [comment]
改动太小

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-bbs/pull/19 看看这个，ps：本pr只是做workflow

**Comment by boomzero** [comment]
I know, but The pr thing is too over-complicated

**Review by boomzero — APPROVED** [review]
But, I suppose there is nothing to review anyways

**Pull request merged**
