### PR TITLE
正常的导航栏

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。
@PythonSmall-Q 现在完全可以了

### CODE REVIEW

**Comment by PythonSmall-Q** [comment]
Sure, I can help with that! Here are a few potential vulnerabilities and improvements for your `NavbarStyler` class:

1. **DOM Manipulation Safety**:
[ ]   - **Element Existence**: Ensure that `this.navbar` and other elements like `#blur-overlay` and `#navbar-spacer` exist before manipulating them to avoid potential `null` or `undefined` errors.
[ ]   - **UtilityEnabled Function**: Make sure the `UtilityEnabled("NewTopBar")` function is secure and cannot be tampered with.

2. **Event Listener Management**:
[ ]   - **Memory Leaks**: The `resize` event listener is added but never removed. Consider removing it when it's no longer needed to prevent memory leaks.
   ```javascript
   window.addEventListener('resize', this.updateBlurOverlay);
   // Later, remove the event listener if necessary
   window.removeEventListener('resize', this.updateBlurOverlay);
   ```

3. **CSS Injection**:
[ ]   - **Style Injection**: Directly injecting styles via JavaScript can be risky. Consider using predefined CSS classes instead of inline styles to avoid potential CSS injection attacks.
   ```javascript
   n.classList.add('fixed-top', 'container', 'ml-auto', 'custom-navbar-style');
   ```

4. **Security Headers**:
 [ ]   - **Content Security Policy (CSP)**: Ensure your site has a strong CSP to prevent cross-site scripting (XSS) attacks, especially since you're dynamically creating and injecting elements and styles.

5. **Performance**:
[ ]   - **Reflows and Repaints**: Frequent DOM manipulations, like updating the overlay's position and size on every resize event, can cause performance issues. Consider debouncing the `resize` event handler.
   ```javascript
   window.addEventListener('resize', debounce(this.updateBlurOverlay, 100));
   
   function debounce(func, wait) {
       let timeout;
       return function(...args) {
           clearTimeout(timeout);
           timeout = setTimeout(() => func.apply(this, args), wait);
       };
   }
   ```

6. **Accessibility**:
[ ]    - **ARIA Attributes**: Ensure that the dynamically created elements are accessible. For example, adding appropriate ARIA roles and properties to the overlay and spacer elements.

By addressing these points, you can improve the security, performance, and accessibility of your `NavbarStyler` class. If you have any specific concerns or need further assistance, feel free to ask!

Source: Conversation with Copilot, 2024/8/2
(1) CSS Navigation Bar - W3Schools. https://www.w3schools.com/Css/css_navbar.asp.
(2) How To Create a Dropdown Navigation Bar - W3Schools. https://www.w3schools.com/howto/howto_css_dropdown_navbar.asp.
(3) Creating a Responsive Navbar with HTML, CSS, and JavaScript. https://www.aleksandrhovhannisyan.com/blog/responsive-navbar-tutorial/.

**Comment by zhouyiqing0304** [comment]
> Sure, I can help with that! Here are a few potential vulnerabilities and improvements for your `NavbarStyler` class:
> 
> 1. **DOM Manipulation Safety**:
>    [ ]   - **Element Existence**: Ensure that `this.navbar` and other elements like `#blur-overlay` and `#navbar-spacer` exist before manipulating them to avoid potential `null` or `undefined` errors.
>    [ ]   - **UtilityEnabled Function**: Make sure the `UtilityEnabled("NewTopBar")` function is secure and cannot be tampered with.
> 2. **Event Listener Management**:
>    [ ]   - **Memory Leaks**: The `resize` event listener is added but never removed. Consider removing it when it's no longer needed to prevent memory leaks.
>    ```js
>    window.addEventListener('resize', this.updateBlurOverlay);
>    // Later, remove the event listener if necessary
>    window.removeEventListener('resize', this.updateBlurOverlay);
>    ```
> 3. **CSS Injection**:
>    [ ]   - **Style Injection**: Directly injecting styles via JavaScript can be risky. Consider using predefined CSS classes instead of inline styles to avoid potential CSS injection attacks.
>    ```js
>    n.classList.add('fixed-top', 'container', 'ml-auto', 'custom-navbar-style');
>    ```
> 4. **Security Headers**:
>    [ ]   - **Content Security Policy (CSP)**: Ensure your site has a strong CSP to prevent cross-site scripting (XSS) attacks, especially since you're dynamically creating and injecting elements and styles.
> 5. **Performance**:
>    [ ]   - **Reflows and Repaints**: Frequent DOM manipulations, like updating the overlay's position and size on every resize event, can cause performance issues. Consider debouncing the `resize` event handler.
>    ```js
>    window.addEventListener('resize', debounce(this.updateBlurOverlay, 100));
>    
>    function debounce(func, wait) {
>        let timeout;
>        return function(...args) {
>            clearTimeout(timeout);
>            timeout = setTimeout(() => func.apply(this, args), wait);
>        };
>    }
>    ```
> 6. **Accessibility**:
>    [ ]    - **ARIA Attributes**: Ensure that the dynamically created elements are accessible. For example, adding appropriate ARIA roles and properties to the overlay and spacer elements.
> 
> By addressing these points, you can improve the security, performance, and accessibility of your `NavbarStyler` class. If you have any specific concerns or need further assistance, feel free to ask!
> 
> Source: Conversation with Copilot, 2024/8/2 (1) CSS Navigation Bar - W3Schools. https://www.w3schools.com/Css/css_navbar.asp. (2) How To Create a Dropdown Navigation Bar - W3Schools. https://www.w3schools.com/howto/howto_css_dropdown_navbar.asp. (3) Creating a Responsive Navbar with HTML, CSS, and JavaScript. https://www.aleksandrhovhannisyan.com/blog/responsive-navbar-tutorial/.

我看看现在去改一下
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
自己看看再改，我看到了很多无关的

**Comment by zhouyiqing0304** [comment]
优化后的代码保持了原有功能的同时，减少了冗余和提高了代码可读性：

js
复制代码
class NavbarStyler {
    constructor() {
        this.navbar = document.querySelector('.navbar.navbar-expand-lg.bg-body-tertiary');
        if (this.navbar && UtilityEnabled("NewTopBar")) {
            this.init();
        }
    }

    init() {
        this.applyStyles();
        this.createOverlay();
        this.createSpacer();
        this.updateBlurOverlay();
        window.addEventListener('resize', this.updateBlurOverlay.bind(this));
    }

    applyStyles() {
        Object.assign(this.navbar.style, {
            position: 'fixed',
            borderRadius: '28px',
            boxShadow: '0 4px 8px rgba(0, 0, 0, 0.5)',
            margin: '8px auto',
            backgroundColor: 'rgba(255, 255, 255, 0)',
            opacity: '0.75',
            zIndex: '1000'
        });
        this.navbar.classList.add('fixed-top', 'container', 'ml-auto');
    }

    createOverlay() {
        if (!document.getElementById('blur-overlay')) {
            const overlay = document.createElement('div');
            overlay.id = 'blur-overlay';
            document.body.appendChild(overlay);

            const style = document.createElement('style');
            style.textContent = `
                #blur-overlay {
                    position: fixed;
                    backdrop-filter: blur(4px);
                    z-index: 999;
                    pointer-events: none;
                    border-radius: 28px;
                }
            `;
            document.head.appendChild(style);
        }
    }

    updateBlurOverlay() {
        const overlay = document.getElementById('blur-overlay');
        Object.assign(overlay.style, {
            top: `${this.navbar.offsetTop}px`,
            left: `${this.navbar.offsetLeft}px`,
            width: `${this.navbar.offsetWidth}px`,
            height: `${this.navbar.offsetHeight}px`
        });
    }

    createSpacer() {
        if (!document.getElementById('navbar-spacer')) {
            const spacer = document.createElement('div');
            spacer.id = 'navbar-spacer';
            spacer.style.height = `${this.navbar.offsetHeight + 8}px`;
            spacer.style.width = '100%';
            document.body.insertBefore(spacer, document.body.firstChild);
        }
    }
}
优化点：
使用 bind(this) 确保 updateBlurOverlay 方法中的 this 指向当前实例。
将 overlay 和 spacer 变量用 const 替换 let，提高代码的清晰度。
将 navbar 的样式应用和类添加合并到一个方法中，减少冗余代码。

**Comment by PythonSmall-Q** [comment]
别用gpt，手改

**Comment by PythonSmall-Q** [comment]
我gpt只是用来查询的

**Comment by zhouyiqing0304** [comment]
肯定啊
但是查询的话Microsoft Copilot更好

**Comment by PythonSmall-Q** [comment]
```
class NavbarStyler {
    constructor() {
        this.navbar = document.querySelector('.navbar.navbar-expand-lg.bg-body-tertiary');
        if (this.navbar && UtilityEnabled("NewTopBar")) {
            this.init();
        }
    }

    init() {
        this.applyStyles();
        this.createOverlay();
        this.createSpacer();
        this.updateBlurOverlay();
        window.addEventListener('resize', () => this.updateBlurOverlay());
    }

    applyStyles() {
        let n = this.navbar;
        n.classList.add('fixed-top', 'container', 'ml-auto');
        Object.assign(n.style, {
            position: 'fixed',
            borderRadius: '28px',
            boxShadow: '0 4px 8px rgba(0, 0, 0, 0.5)',
            margin: '8px auto',
            backgroundColor: 'rgba(255, 255, 255, 0)',
            opacity: '0.75',
            zIndex: '1000'
        });
    }

    createOverlay() {
        if (!document.getElementById('blur-overlay')) {
            let overlay = document.createElement('div');
            overlay.id = 'blur-overlay';
            document.body.appendChild(overlay);

            let style = document.createElement('style');
            style.textContent = `
                #blur-overlay {
                    position: fixed;
                    backdrop-filter: blur(4px);
                    z-index: 999;
                    pointer-events: none;
                    border-radius: 28px;
                }
            `;
            document.head.appendChild(style);
        }
    }

    updateBlurOverlay() {
        let overlay = document.getElementById('blur-overlay');
        let n = this.navbar;
        if (overlay && n) {
            Object.assign(overlay.style, {
                top: `${n.offsetTop}px`,
                left: `${n.offsetLeft}px`,
                width: `${n.offsetWidth}px`,
                height: `${n.offsetHeight}px`
            });
        }
    }

    createSpacer() {
        if (!document.getElementById('navbar-spacer')) {
            let spacer = document.createElement('div');
            spacer.id = 'navbar-spacer';
            spacer.style.height = `${this.navbar.offsetHeight + 8}px`;
            spacer.style.width = '100%';
            document.body.insertBefore(spacer, document.body.firstChild);
        }
    }
}
```

**Comment by zhouyiqing0304** [comment]
你让我改啥

**Comment by PythonSmall-Q** [comment]
你看看这个行不行，能不能跑

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 跑起来完全没问题
我这个代码兼容性不一定绝对好，但是改起来容易跑

**Comment by zhouyiqing0304** [comment]
image

**Review by PythonSmall-Q — CHANGES_REQUESTED** [review]
更新栏！！！again ovo

**Comment by zhouyiqing0304** [comment]
我要用你的还是我改的

**Comment by zhouyiqing0304** [comment]
哦我差点忘记了
我把它加上去

**Comment by PythonSmall-Q** [comment]
用你自己的

**Comment by zhouyiqing0304** [comment]
好的好的

**Review by PythonSmall-Q — CHANGES_REQUESTED** [review]
更新栏和导航栏宽度相同

**Comment by zhouyiqing0304** [comment]
现在可以了
更新没问题，并且保证在关闭更新弹窗之后不会多出来一片空白
正常使用

**Review by PythonSmall-Q — APPROVED** [review]
貌似没问题了

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by zhouyiqing0304** [comment]
@boomzero 经过沟通测试研究之后找到了一个很刁钻的bug，需要1、你的电脑足够慢2、脚本运行足够快3、你的手速比电脑快4、忍不住一顿瞎点 才会出现一块不该出现的空白。我加了几行判定，现在应该是完美的了
恁过一下谢谢

**Comment by PythonSmall-Q** [comment]
触发这个问题的就是我的12th Gen Intel(R) Core(TM) i5-12500H 一般速率4GHz

基准速度:2.50 GHz

插槽:1

内核:12

逻辑处理器:16

虚拟化:已启用

L1 缓存:1.1 MB

L2 缓存:9.0 MB

L3 缓存:18.0 MB













在 2024-08-02 12:53:50，"zhouyiqing0304" ***@***.***> 写道：

@boomzero 经过沟通测试研究之后找到了一个很刁钻的bug，需要1、你的电脑足够慢2、脚本运行足够快3、你的手速比电脑快4、忍不住一顿瞎点 才会出现一块不该出现的空白。我加了几行判定，现在应该是完美的了
恁过一下谢谢

**Comment by zhouyiqing0304** [comment]
很明显，我的i7-12700H就没有出现问题
image

**Comment by zhouyiqing0304** [comment]
image
不怪我把锅甩到电脑上吧

> 很明显，我的i7-12700H就没有出现问题 image

**Comment by zhouyiqing0304** [comment]
> 触发这个问题的就是我的12th Gen Intel(R) Core(TM) i5-12500H 一般速率4GHz 基准速度:2.50 GHz 插槽:1 内核:12 逻辑处理器:16 虚拟化:已启用 L1 缓存:1.1 MB L2 缓存:9.0 MB L3 缓存:18.0 MB 在 2024-08-02 12:53:50，"zhouyiqing0304" ***@***.***> 写道： @boomzero 经过沟通测试研究之后找到了一个很刁钻的bug，需要1、你的电脑足够慢2、脚本运行足够快3、你的手速比电脑快4、忍不住一顿瞎点 才会出现一块不该出现的空白。我加了几行判定，现在应该是完美的了 恁过一下谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***>

但是Chromium有时候会抽那么一两下，所以必须要不断判定
@boomzero 你说是不是

**Pull request merged**
