### PR TITLE
Update XMOJ.user.js

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.

I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 这样可以了吧

**Comment by PythonSmall-Q** [comment]
image
这是什么？？？

还有，要等所有的action都运行完才能merge，否则版本号改不了

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 还有，pr的名字要好好写，否则更新内容不对！！！！

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 你不要随便merge，
image
点这个的让我们approve再merge

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 你把游戏软件加进去就不好了

**Comment by PythonSmall-Q** [comment]
那个watt toolkit是游戏软件，在这样就把你提出去了哦~

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q Watt Toolkit看似是一个steam加速软件，实则是用来加速GitHub的（否则连不上啊）

**Comment by zhouyiqing0304** [comment]
要不然人家怎么提交issues怎么反馈bug

**Comment by zhouyiqing0304** [comment]
我研究一下脚本，看可不可以用脚本来完成加速事情

**Comment by zhouyiqing0304** [comment]
image

**Comment by langningchen** [comment]
> 我研究一下脚本，看可不可以用脚本来完成加速事情

@zhouyiqing0304 请遵守中华人民共和国法律

**Comment by boomzero** [comment]
…在 2024年2月17日，22:01，Langning Chen ***@***.***> 写道：﻿

我研究一下脚本，看可不可以用脚本来完成加速事情

@zhouyiqing0304 请遵守中华人民共和国法律

**Comment by PythonSmall-Q** [comment]
你加油哈我们都初三了要中考了，都要开始感情生活了（bushi

**Comment by boomzero** [comment]
…在 2024年2月18日，17:27，Shan Wenxiao ***@***.***> 写道：﻿
你加油哈我们都初三了要中考了，都要开始感情生活了（bushi

**Pull request merged**
