### PR TITLE
Sync Dev

### PR DESCRIPTION
**Pull request by boomzero**
This will probably be my last pr until July.

### CODE REVIEW

**Review by PythonSmall-Q — DISMISSED** [review]

**Comment by PythonSmall-Q** [comment]
我在疯狂的fix sitemap

**Comment by PythonSmall-Q** [comment]
Update to release炸了？？

**Comment by boomzero** [comment]
> Update to release炸了？？

没有

**Comment by PythonSmall-Q** [comment]
Failing after 9s

**Review by PythonSmall-Q — APPROVED** [review]

**Pull request merged**
