### PR TITLE
解决报名月赛页面没有脚本显示、没有月赛仍显示报名信息并可以提交报名的问题

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
## Thank you for your contribution to the XMOJ-Script Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

Please use this pull request template, or your pull request will be closed.

**Please make sure you**

1. Base your code and PRs against the repositories developmental branch.

### When you open a pull request, please delete the text above.
---

**What does this PR aim to accomplish?:**

**How does this PR accomplish the above?:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/dev/CONTRIBUTING.md), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [GNU General Public License v3.0](https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/dev/LICENSE)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [ ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@boomzero @PythonSmall-Q 
https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/620

**Review by PythonSmall-Q — CHANGES_REQUESTED** [review]
其实还有一个问题，就是又可以报名的月赛会直接显示报名内容，不让你选

**Comment by PythonSmall-Q** [comment]
所以当时就把这一页关掉了

**Comment by boomzero** [comment]
月赛报名时会出锅

**Comment by boomzero** [comment]
所以才关了

**Pull request closed without merging**
