### PR TITLE
revert #514

### PR DESCRIPTION
**Pull request by boomzero**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

### CODE REVIEW

**Comment by boomzero** [comment]
This caused more bugs than it solved.

**Comment by zhouyiqing0304** [comment]
i see

**Comment by boomzero** [comment]
We are aware of issues with Pagination.

**Comment by boomzero** [comment]
> We are aware of issues with Pagination.

This issue is resolved using a backend update, making your changes unnecessary.

**Pull request merged**
