### PR TITLE
Zhouyiqing0304 patch 2

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.

I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q 过一下

**Comment by PythonSmall-Q** [comment]
我看看

**Comment by PythonSmall-Q** [comment]
等一下，你改了啥？你要到dev里面修改，然后pr到dev

**Comment by PythonSmall-Q** [comment]
否则全是conflict

**Comment by PythonSmall-Q** [comment]
我先试试能不能解决

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 
image
这两个“- -”干嘛？？？

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/428 @zhouyiqing0304

**Pull request closed without merging**
